### ISSUE TITLE
Photonize remaining toolbar icons

### ISSUE THREAD

**Issue by fvsch** [devtools-html/ux#47]
Our update-icons-to-Photon-style issues:

- [x] RDM button and Frames button #18
- [x] Other toolbox button icons #26
- [x] Toolbox tab icons #36
- [ ] RDM toolbar icons #28 (in progress)

Let's do a pass for the remaining icons, especially those used in different tool's toolbars. We can focus on the most visible first, but it would great to group work on a bunch of icons to help achieve a consistent look. Ideally we can land an update in Firefox 66 beta (merge date 2019-01-28).

I'll try to take the lead on this, but any help is welcome.
There are existing 16px Firefox for desktop icons we can reuse:
https://github.com/FirefoxUX/photon-icons/tree/master/icons/desktop

Tried an eyedropper icon here:
https://www.figma.com/file/XxOXCNeJu3PbRxdFRNgCyfDb/Eyedropper-icon

**Comment by fvsch** [comment]
5 icons ready to land in [bug 1513516](https://bugzilla.mozilla.org/show_bug.cgi?id=1513516), waiting for ui review for the stopwatch icon.

**Comment by fvsch** [comment]
I started a Figma document for updating a few remaining icons from Inspector and other tools.
https://www.figma.com/file/gZ2qwGfvs35fbvYtrb2uL41m/DevTools-Misc-Icons
Not including Debugger play/pause/step icons alone for now.

**Comment by violasong** [comment]
- I like eye wide open, and would just suggest a large iris so that it's friendlier looking.
- The eye closed is clever and does seem like a really good idea for accessibility. I have to admit though, increasing the metaphor here does strike me as a tad creepy - I don't really want to think of little blinkable cyclops eyes in my UI. Maybe Sketch's solution of a crossed-out eye would be better.
- Stopwatch looks great.
- Love the small/bold search icon.
- Simple filter icon looks great! (I prefer it to the 3 lines)
- Eyedropper: beautiful examples. The figma one totally looks better due to the squeeze part actually looking squeezable. The photonic one on the second row could probably also be modified to be more similarly realistic, but I'm happy to go with the figma one for now.

**Comment by fvsch** [comment]
A crossed-out eye could be good, and follows conventions used for several Photon icons too.

Let's start with implementing search, filter and the color picker icon. Filed [bug 1522041](https://bugzilla.mozilla.org/show_bug.cgi?id=1522041) for that.

**Comment by mcroud** [comment]
These are super.

Both the wide-open and normal eye feel like improvements to me, I would be happy with either.
Doing a Google image search for "Hide icon" falls in favor of Victoria's suggestion of using a crossed-out eye. Another pattern is placing the eye within a box and having the alternative hidden state being just the box (removing the eye), like a checkbox. Adobe do this with layers, so it might appeal to the Style Editor but maybe not much else. 
The profiler stopwatch requires much less guesswork on the users part than the current offering, definately a winner for me.
Search icons look more appealing with a thicker, Photonised handle, Good good.
I must say I do like the 16px oblique-end filter, my only question is if we go with the Figma style pipet are there any other icons which use a semi-transparent fill?
Funny, when I saw the three line filter here I thought to myself "I've never seen that in the wild before?" Then yesterday afternoon I saw that Airtable were using it for their filter button 😆
The three lines could grow on me but the traditional filter feels more in place beside the other, more physical representative icons.  
For the eyedropper, again I'll echo what Victoria has said here, the Figma style pipet looks much more solid, friendlier and feels right next to the other icons.

**Comment by fvsch** [comment]
Search, Filter and Eyedropper icons landing later today. :)
